# Clients can connect to the servers via a unique service
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: server
spec:
  selector:
    matchLabels:
      name: server
  template:
    metadata:
      labels:
        name: server
        collector: netflow
    spec:
      containers:
        - name: server
          image: quay.io/mmaciasl/sticky-test-server:latest
          imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: server
spec:
  type: NodePort
  #Disabled, as requires:
  #internalTrafficPolicy: Local
  selector:
    name: server
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io